Feature/17 were created permissions tables
gitkoshelew/CC.api pull request #20
Opened 2023-01-03 10:57 UTC by FaridKarmanov

2023-01-04 11:41 UTC, gitkoshelew approved these changes

2023-01-04 11:44 UTC, YuryHouse submitted a review, later dismissed

2023-01-04 12:44 UTC, PrimkY requested changes

2023-01-04 12:44 UTC, PrimkY commented on src/permission/permission.model.ts
> +  @Column({type: DataType.INTEGER})
### column has been created but never used

2023-01-04 12:44 UTC, PrimkY commented on src/permission/permission.module.ts
> +    imports: [SequelizeModule.forFeature([Permission, PermissionGroup])],
## create export for permissions and import them into permission group. create functions to CRUD permissions at permission group

2023-01-10 13:13 UTC, PrimkY approved these changes

2023-01-11 09:41 UTC, YuryHouse approved these changes

2023-01-11 10:16 UTC, merged